
DATA_FILE_BASE = './'
LOG_FILE_BASE = 'logs/'
MODEL_FILE_BASE = 'models/'
SUBMISSION_FILE_BASE = 'submissions/'


ORIGIN_DATA_FILE = DATA_FILE_BASE + 'train.csv'
TRAIN_DATA_FILE = DATA_FILE_BASE + 'train_data.csv'
VALIDATE_DATA_FILE = DATA_FILE_BASE + 'validate_data.csv'
EXPANDED_TRAIN_DATA_FILE = DATA_FILE_BASE + 'train_data_expand.csv'
TEST_DATA_FILE = DATA_FILE_BASE + 'test.csv'

VALIDATE_DATA_PROPORTION = 0.2

IMG_SIZE = 28
EXPAND_OFFSET = 2

ADAM_OPTIMIZER_LEARNING_RATE = 1e-4